datas:
    origin_train_path: /media/htb/data/dataset/nlp/stock-data/train_data
    origin_test_path: /media/htb/data/dataset/nlp/stock-data/test_data
    generate_train_path: ./datas/train_data.csv
    generate_validate_path: ./datas/validate_data.csv
    generate_test_path: ./datas/test_data.csv

    is_regenerate_train_data: 0
    is_regenerate_test_data: 0
    split_validate_size: 0.1

    is_standardization: 1
    is_neutralization: 0
    is_remove_extreme: 1
    is_cross_validate: 0
    is_split_validate: 1

models:
    model_path: ./save
    log_path: ./logs
    model_name: GradientBoostingRegressor
    all_model_name: [
        "SGDRegressor",
        "HuberRegressor",
        "LinearRegression",
        "LinearSVR",
        "BaggingRegressor",
        "AdaBoostRegressor",
        "ExtraTreesRegressor",
        "RandomForestRegressor",
        "GradientBoostingRegressor"
    ]
